const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const Content = require('../models/Content');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/nexplay';

// ═══════════════════════════════════════════════════════════════
// IMAGE GENERATION HELPERS
// Every title gets a unique, deterministic, ALWAYS-LOADING image.
// (The previous TMDB paths were fabricated and duplicated across
// unrelated titles, so they were either broken or wrong.)
// ═══════════════════════════════════════════════════════════════
function slugify(title) {
  return title
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '') // strip accents
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function posterFor(title) {
  const slug = slugify(title);
  return `https://picsum.photos/seed/${slug}-poster/500/750`;
}

function backdropFor(title) {
  const slug = slugify(title);
  return `https://picsum.photos/seed/${slug}-backdrop/1280/720`;
}

// Real TMDB poster image paths
const contentData = [
  // ═══════════════════════════════════════════════════════════════
  // MOVIES
  // ═══════════════════════════════════════════════════════════════
  {
    title: 'Crimson Horizon',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A fearless astronaut leads a desperate mission to a rogue planet heading toward Earth, discovering an ancient alien civilization that holds the key to humanity\'s survival.',
    genres: ['Sci-Fi', 'Adventure', 'Thriller'],
    tags: ['space', 'survival', 'alien', 'expedition'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 5,
    rating: 8.1,
    status: 'Released',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 88,
    trending: 85
  },
  {
    title: 'The Whispering Pines',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A family moves to a remote cabin in the Pacific Northwest only to discover that the ancient forest around them harbors a malevolent supernatural entity.',
    genres: ['Horror', 'Mystery', 'Thriller'],
    tags: ['horror', 'supernatural', 'forest', 'family'],
    spokenLanguage: 'English',
    releaseYear: 2023,
    releaseMonth: 9,
    rating: 7.6,
    status: 'Released',
    platforms: ['HBO Max', 'Amazon Prime'],
    popularity: 72,
    trending: 68
  },
  {
    title: 'Neon Samurai',
    originalTitle: 'ネオン侍',
    type: 'MOVIE',
    description: 'In a cyberpunk Tokyo of 2099, a disgraced samurai turned bounty hunter uncovers a corporate conspiracy that threatens to erase the city\'s cultural heritage.',
    genres: ['Action', 'Sci-Fi', 'Cyberpunk'],
    tags: ['cyberpunk', 'japanese', 'samurai', 'dystopian'],
    spokenLanguage: 'Japanese',
    releaseYear: 2024,
    releaseMonth: 2,
    rating: 8.3,
    status: 'Released',
    platforms: ['Netflix', 'Crunchyroll'],
    popularity: 84,
    trending: 82
  },
  {
    title: 'Glass Cathedral',
    originalTitle: '',
    type: 'MOVIE',
    description: 'An art forger is recruited by a shadowy organization to steal a priceless stained-glass masterpiece from a Vatican vault, leading to an international conspiracy.',
    genres: ['Thriller', 'Crime', 'Mystery'],
    tags: ['heist', 'art', 'vatican', 'suspense'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 6,
    rating: 7.9,
    status: 'Released',
    platforms: ['Amazon Prime', 'Apple TV+'],
    popularity: 76,
    trending: 71
  },
  {
    title: 'Monsoon Wedding Revisited',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A sprawling family dramedy set during a lavish three-day wedding in Udaipur, where long-buried secrets and unexpected romances surface under the monsoon rains.',
    genres: ['Drama', 'Comedy', 'Romance'],
    tags: ['indian', 'wedding', 'family', 'drama'],
    spokenLanguage: 'Hindi',
    releaseYear: 2024,
    releaseMonth: 7,
    rating: 8.0,
    status: 'Released',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 74,
    trending: 70
  },
  {
    title: 'Echoes of Tomorrow',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A quantum physicist discovers she can send messages 24 hours into the past, but each use fractures reality further, threatening to unravel the space-time continuum.',
    genres: ['Sci-Fi', 'Thriller', 'Drama'],
    tags: ['time-travel', 'quantum', 'sci-fi', 'paradox'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 1,
    rating: 8.5,
    status: 'Released',
    platforms: ['Apple TV+', 'Amazon Prime'],
    popularity: 82,
    trending: 79
  },
  {
    title: 'Burning Sands',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A war correspondent stranded in a desert war zone must navigate rival factions and treacherous terrain to deliver evidence of a massacre to the outside world.',
    genres: ['Action', 'War', 'Drama'],
    tags: ['war', 'desert', 'journalist', 'survival'],
    spokenLanguage: 'English',
    releaseYear: 2023,
    releaseMonth: 10,
    rating: 7.8,
    status: 'Released',
    platforms: ['Netflix', 'HBO Max'],
    popularity: 70,
    trending: 65
  },
  {
    title: 'Silver Lotus',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A martial arts master in 1930s Shanghai protects her temple from Japanese invaders while searching for her long-lost brother who has joined the occupying forces.',
    genres: ['Action', 'Historical', 'Drama'],
    tags: ['martial-arts', 'historical', 'china', 'war'],
    spokenLanguage: 'Mandarin',
    releaseYear: 2024,
    releaseMonth: 3,
    rating: 8.2,
    status: 'Released',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 78,
    trending: 75
  },
  {
    title: 'The Last Lighthouse',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A retired lighthouse keeper in remote Iceland must defend his home from a ruthless corporation trying to seize the land for a luxury resort, using only his wits and the sea.',
    genres: ['Drama', 'Thriller'],
    tags: ['iceland', 'lighthouse', 'survival', 'nature'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 11,
    rating: 7.7,
    status: 'Released',
    platforms: ['Amazon Prime', 'Apple TV+'],
    popularity: 65,
    trending: 60
  },
  {
    title: 'Carnival of Shadows',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A traveling carnival arrives in a small Depression-era town, bringing with it a mysterious ringmaster whose dark magic begins to corrupt the townspeople one by one.',
    genres: ['Fantasy', 'Horror', 'Mystery'],
    tags: ['carnival', 'supernatural', '1930s', 'dark-fantasy'],
    spokenLanguage: 'English',
    releaseYear: 2023,
    releaseMonth: 8,
    rating: 7.5,
    status: 'Released',
    platforms: ['HBO Max', 'Hulu'],
    popularity: 68,
    trending: 64
  },
  {
    title: 'Phantom Express',
    originalTitle: '',
    type: 'MOVIE',
    description: 'Passengers aboard a luxury transcontinental train in 1912 discover that one of them is a serial killer, and the train won\'t stop until someone is caught.',
    genres: ['Mystery', 'Thriller', 'Crime'],
    tags: ['train', 'murder-mystery', 'period-piece', 'suspense'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 4,
    rating: 8.0,
    status: 'Released',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 80,
    trending: 77
  },
  {
    title: 'Tidal Wave',
    originalTitle: '해일',
    type: 'MOVIE',
    description: 'A marine biologist races against time to warn a coastal city of an impending mega-tsunami while dealing with corrupt officials who refuse to believe the science.',
    genres: ['Action', 'Thriller', 'Disaster'],
    tags: ['korean', 'disaster', 'tsunami', 'survival'],
    spokenLanguage: 'Korean',
    releaseYear: 2024,
    releaseMonth: 8,
    rating: 7.8,
    status: 'Released',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 79,
    trending: 76
  },
  {
    title: 'Velvet Underground',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A gritty biopic following the rise of a fictional 1970s rock band through the seedy underbelly of New York\'s music scene, exploring fame, addiction, and artistic integrity.',
    genres: ['Drama', 'Music', 'Biography'],
    tags: ['music', '70s', 'rock-band', 'new-york'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 3,
    rating: 8.4,
    status: 'Released',
    platforms: ['Amazon Prime', 'HBO Max'],
    popularity: 77,
    trending: 73
  },
  {
    title: 'Midnight in Marrakech',
    originalTitle: '',
    type: 'MOVIE',
    description: 'An American travel writer stumbles into a web of intrigue and romance in the labyrinthine souks of Marrakech, where nothing and no one are as they appear.',
    genres: ['Romance', 'Thriller', 'Mystery'],
    tags: ['morocco', 'romance', 'mystery', 'travel'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 11,
    rating: 7.4,
    status: 'Released',
    platforms: ['Netflix', 'Apple TV+'],
    popularity: 63,
    trending: 58
  },
  {
    title: 'Code Breaker',
    originalTitle: '',
    type: 'MOVIE',
    description: 'The untold story of a team of British codebreakers during WWII who cracked an unbreakable Nazi cipher, changing the course of the war through sheer intellect and sacrifice.',
    genres: ['Historical', 'Thriller', 'Drama'],
    tags: ['wwii', 'codebreaking', 'historical', 'british'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 10,
    rating: 8.6,
    status: 'Released',
    platforms: ['Apple TV+', 'Amazon Prime'],
    popularity: 81,
    trending: 78
  },
  {
    title: 'The Desert Fox',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A lone survivor of a plane crash in the Sahara must outwit armed bandits, survive extreme conditions, and find his way back to civilization with an injured companion.',
    genres: ['Adventure', 'Thriller', 'Drama'],
    tags: ['desert', 'survival', 'plane-crash', 'adventure'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 2,
    rating: 7.9,
    status: 'Released',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 75,
    trending: 72
  },
  {
    title: 'Temple of the Sun',
    originalTitle: 'Solens Tempel',
    type: 'MOVIE',
    description: 'An archaeologist disappears while searching for a lost Inca city in the Amazon. His daughter follows his trail, uncovering an ancient secret that indigenous tribes have protected for centuries.',
    genres: ['Adventure', 'Mystery', 'Action'],
    tags: ['archaeology', 'amazon', 'inca', 'adventure'],
    spokenLanguage: 'Spanish',
    releaseYear: 2024,
    releaseMonth: 9,
    rating: 7.7,
    status: 'Released',
    platforms: ['Netflix', 'HBO Max'],
    popularity: 71,
    trending: 67
  },
  {
    title: 'Upcoming: Aurora Station',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A crew of scientists aboard a space station in 2085 discovers a mysterious signal coming from a parallel dimension, opening a doorway to infinite possibilities and unimaginable danger.',
    genres: ['Sci-Fi', 'Thriller', 'Mystery'],
    tags: ['space-station', 'parallel-dimension', 'sci-fi', 'upcoming'],
    spokenLanguage: 'English',
    releaseYear: 2026,
    releaseMonth: 3,
    rating: 0,
    status: 'Upcoming',
    platforms: ['Netflix'],
    popularity: 55,
    trending: 70
  },
  {
    title: 'Upcoming: Emerald City',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A dark reimagining of The Wizard of Oz set in a dystopian future where Dorothy returns to a crumbling Emerald City ruled by a corrupt AI-powered Wizard.',
    genres: ['Fantasy', 'Sci-Fi', 'Adventure'],
    tags: ['fantasy', 'reimagining', 'dystopian', 'upcoming'],
    spokenLanguage: 'English',
    releaseYear: 2026,
    releaseMonth: 7,
    rating: 0,
    status: 'Upcoming',
    platforms: ['HBO Max'],
    popularity: 48,
    trending: 65
  },
  {
    title: 'Upcoming: Ganges Rising',
    originalTitle: 'गंगा उफनती',
    type: 'MOVIE',
    description: 'A gripping environmental thriller set in Varanasi where a young activist takes on a powerful industrial conglomerate polluting the sacred Ganges river.',
    genres: ['Drama', 'Thriller'],
    tags: ['indian', 'environment', 'activism', 'upcoming'],
    spokenLanguage: 'Hindi',
    releaseYear: 2026,
    releaseMonth: 5,
    rating: 0,
    status: 'Upcoming',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 42,
    trending: 58
  },
  {
    title: 'Mirage',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A heart surgeon begins experiencing visions of a life she never lived — as a concert pianist in 1950s Paris — and must uncover the truth before both realities collapse.',
    genres: ['Drama', 'Mystery', 'Romance'],
    tags: ['parallel-lives', 'mystery', 'romance', 'drama'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 4,
    rating: 8.1,
    status: 'Released',
    platforms: ['Apple TV+', 'Amazon Prime'],
    popularity: 73,
    trending: 69
  },
  {
    title: 'The Iron Dragon',
    originalTitle: '铁龙',
    type: 'MOVIE',
    description: 'In a steampunk version of Qing Dynasty China, a brilliant inventor builds a mechanical dragon to defend Beijing from foreign invaders and corrupt warlords.',
    genres: ['Action', 'Steampunk', 'Historical'],
    tags: ['steampunk', 'china', 'historical-fiction', 'invention'],
    spokenLanguage: 'Mandarin',
    releaseYear: 2025,
    releaseMonth: 6,
    rating: 7.6,
    status: 'Released',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 69,
    trending: 66
  },
  {
    title: 'Frozen Hearts',
    originalTitle: '',
    type: 'MOVIE',
    description: 'Two rival mountaineers stranded in a blizzard on K2 must put aside their animosity to survive, forging an unlikely bond in the deadliest conditions on Earth.',
    genres: ['Adventure', 'Drama', 'Survival'],
    tags: ['mountaineering', 'survival', 'k2', 'adventure'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 8,
    rating: 8.2,
    status: 'Released',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 78,
    trending: 74
  },
  {
    title: 'Samba Showdown',
    originalTitle: 'Batalha de Samba',
    type: 'MOVIE',
    description: 'A vibrant musical set in Rio de Janeiro\'s favelas during Carnival, where rival samba schools compete for glory while dealing with gang violence and political corruption.',
    genres: ['Musical', 'Drama', 'Crime'],
    tags: ['brazil', 'samba', 'carnival', 'musical'],
    spokenLanguage: 'Portuguese',
    releaseYear: 2025,
    releaseMonth: 2,
    rating: 7.8,
    status: 'Released',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 66,
    trending: 62
  },
  {
    title: 'The Cartographer\'s Daughter',
    originalTitle: '',
    type: 'MOVIE',
    description: 'A young woman inherits her father\'s mysterious map collection and embarks on a global treasure hunt that reveals a hidden history of female explorers erased from the records.',
    genres: ['Adventure', 'Mystery', 'Historical'],
    tags: ['treasure-hunt', 'maps', 'exploration', 'feminist'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 9,
    rating: 7.9,
    status: 'Released',
    platforms: ['Apple TV+', 'Amazon Prime'],
    popularity: 64,
    trending: 61
  },

  // ═══════════════════════════════════════════════════════════════
  // TV SERIES
  // ═══════════════════════════════════════════════════════════════
  {
    title: 'Shadow Protocol',
    originalTitle: '',
    type: 'TV_SERIES',
    description: 'A covert intelligence agency operates in the shadows, handling threats too dangerous for the public to know. When a mole is discovered, trust becomes the most lethal weapon.',
    genres: ['Thriller', 'Action', 'Spy'],
    tags: ['spy', 'intelligence', 'conspiracy', 'thriller'],
    spokenLanguage: 'English',
    releaseYear: 2023,
    releaseMonth: 1,
    rating: 8.5,
    status: 'Ongoing',
    platforms: ['Amazon Prime', 'Netflix'],
    popularity: 90,
    trending: 88,
    episodeCount: 16,
    currentEpisode: 16
  },
  {
    title: 'Red Mercury',
    originalTitle: '',
    type: 'TV_SERIES',
    description: 'A chemical engineer discovers her company is secretly manufacturing a devastating biological weapon. She goes on the run with her family, pursued by corporate assassins and corrupt government agents.',
    genres: ['Thriller', 'Drama', 'Action'],
    tags: ['conspiracy', 'bio-weapon', 'on-the-run', 'thriller'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 3,
    rating: 8.2,
    status: 'Ongoing',
    platforms: ['Netflix'],
    popularity: 86,
    trending: 84,
    episodeCount: 10,
    currentEpisode: 10
  },
  {
    title: 'Lunar Colony',
    originalTitle: '',
    type: 'TV_SERIES',
    description: 'The first permanent human settlement on the moon faces political intrigue, resource wars, and the discovery of an alien artifact that could change everything we know about our solar system.',
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    tags: ['moon', 'space-colony', 'sci-fi', 'politics'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 6,
    rating: 8.6,
    status: 'Ongoing',
    platforms: ['Apple TV+', 'Amazon Prime'],
    popularity: 88,
    trending: 86,
    episodeCount: 12,
    currentEpisode: 12
  },
  {
    title: 'Copenhagen Noir',
    originalTitle: 'København Noir',
    type: 'TV_SERIES',
    description: 'A brooding detective in Copenhagen investigates a series of ritualistic murders that connect to an ancient Nordic cult believed to have been extinct for centuries.',
    genres: ['Crime', 'Mystery', 'Thriller'],
    tags: ['scandinavian', 'noir', 'detective', 'cult'],
    spokenLanguage: 'Danish',
    releaseYear: 2023,
    releaseMonth: 9,
    rating: 8.4,
    status: 'Completed',
    platforms: ['Netflix', 'HBO Max'],
    popularity: 82,
    trending: 77,
    episodeCount: 24,
    currentEpisode: 24
  },
  {
    title: 'Bangkok Undercover',
    originalTitle: 'บางกอก อันเดอร์คัฟเวอร์',
    type: 'TV_SERIES',
    description: 'An undercover police officer infiltrates Bangkok\'s most dangerous crime syndicate. As she rises through the ranks, the line between justice and criminality blurs beyond recognition.',
    genres: ['Crime', 'Action', 'Drama'],
    tags: ['thai', 'undercover', 'crime-syndicate', 'bangkok'],
    spokenLanguage: 'Thai',
    releaseYear: 2024,
    releaseMonth: 4,
    rating: 7.9,
    status: 'Ongoing',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 79,
    trending: 76,
    episodeCount: 8,
    currentEpisode: 8
  },
  {
    title: 'The Guild of Shadows',
    originalTitle: '',
    type: 'TV_SERIES',
    description: 'In a world where magical guilds vie for control of modern-day London, a young orphan discovers she is the last heir to a legendary line of shadow mages.',
    genres: ['Fantasy', 'Action', 'Drama'],
    tags: ['magic', 'guilds', 'london', 'urban-fantasy'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 10,
    rating: 8.3,
    status: 'Ongoing',
    platforms: ['Netflix', 'HBO Max'],
    popularity: 87,
    trending: 85,
    episodeCount: 14,
    currentEpisode: 14
  },
  {
    title: 'Sahara Blues',
    originalTitle: '',
    type: 'TV_SERIES',
    description: 'A blues musician travels across North Africa in the 1950s, encountering love, loss, and political upheaval while searching for the origins of a legendary song.',
    genres: ['Drama', 'Music', 'Historical'],
    tags: ['music', 'north-africa', '1950s', 'journey'],
    spokenLanguage: 'English',
    releaseYear: 2023,
    releaseMonth: 5,
    rating: 8.0,
    status: 'Completed',
    platforms: ['Amazon Prime'],
    popularity: 72,
    trending: 68,
    episodeCount: 18,
    currentEpisode: 18
  },
  {
    title: 'Quantum City',
    originalTitle: '',
    type: 'TV_SERIES',
    description: 'A brilliant but reckless physicist accidentally opens a portal to a parallel Earth in downtown Manhattan, creating chaos as alternate versions of people begin crossing over.',
    genres: ['Sci-Fi', 'Comedy', 'Drama'],
    tags: ['parallel-universe', 'sci-fi', 'comedy', 'new-york'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 1,
    rating: 8.1,
    status: 'Ongoing',
    platforms: ['Apple TV+', 'Amazon Prime'],
    popularity: 83,
    trending: 81,
    episodeCount: 6,
    currentEpisode: 6
  },
  {
    title: 'The Mumbai Job',
    originalTitle: 'मुंबई जॉब',
    type: 'TV_SERIES',
    description: 'A team of misfit con artists in Mumbai is recruited by a mysterious benefactor to pull off the biggest heist in Indian history — stealing a priceless Koh-i-Noor replica from a billionaire\'s vault.',
    genres: ['Crime', 'Comedy', 'Thriller'],
    tags: ['heist', 'mumbai', 'con-artists', 'comedy-thriller'],
    spokenLanguage: 'Hindi',
    releaseYear: 2024,
    releaseMonth: 8,
    rating: 8.3,
    status: 'Ongoing',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 85,
    trending: 82,
    episodeCount: 11,
    currentEpisode: 11
  },
  {
    title: 'Frozen North',
    originalTitle: '',
    type: 'TV_SERIES',
    description: 'A small Alaskan town becomes isolated after a catastrophic blizzard. As supplies dwindle, the residents discover a darker threat lurking beneath the ice.',
    genres: ['Horror', 'Thriller', 'Survival'],
    tags: ['alaska', 'survival', 'horror', 'isolation'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 11,
    rating: 7.8,
    status: 'Ongoing',
    platforms: ['Netflix', 'HBO Max'],
    popularity: 76,
    trending: 73,
    episodeCount: 8,
    currentEpisode: 8
  },
  {
    title: 'Empire of Dust',
    originalTitle: '',
    type: 'TV_SERIES',
    description: 'A sweeping historical epic following the rise and fall of a fictional Central Asian empire, told through the eyes of a slave girl who becomes its most powerful empress.',
    genres: ['Historical', 'Drama', 'Adventure'],
    tags: ['historical-epic', 'central-asia', 'empire', 'power'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 2,
    rating: 8.8,
    status: 'Completed',
    platforms: ['HBO Max', 'Amazon Prime'],
    popularity: 91,
    trending: 87,
    episodeCount: 32,
    currentEpisode: 32
  },
  {
    title: 'Cable Street',
    originalTitle: '',
    type: 'TV_SERIES',
    description: 'A gritty London crime drama set in the East End, following three generations of a family navigating gangland politics, gentrification, and changing loyalties.',
    genres: ['Crime', 'Drama', 'Thriller'],
    tags: ['london', 'crime-family', 'east-end', 'gangster'],
    spokenLanguage: 'English',
    releaseYear: 2023,
    releaseMonth: 7,
    rating: 8.5,
    status: 'Ongoing',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 84,
    trending: 80,
    episodeCount: 21,
    currentEpisode: 21
  },
  {
    title: 'Tropical Lies',
    originalTitle: '',
    type: 'TV_SERIES',
    description: 'A luxury resort in Bali becomes the setting for a deadly game of deception when a guest is found murdered. Every employee and guest has a secret worth killing for.',
    genres: ['Mystery', 'Thriller', 'Drama'],
    tags: ['bali', 'resort', 'murder-mystery', 'suspense'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 3,
    rating: 7.7,
    status: 'Ongoing',
    platforms: ['Netflix'],
    popularity: 74,
    trending: 71,
    episodeCount: 8,
    currentEpisode: 8
  },
  {
    title: 'The Resistance',
    originalTitle: 'المقاومة',
    type: 'TV_SERIES',
    description: 'A gripping drama set in occupied territory during wartime, following a group of ordinary citizens who form an underground resistance movement to protect their community.',
    genres: ['Drama', 'War', 'Historical'],
    tags: ['resistance', 'war', 'survival', 'occupied'],
    spokenLanguage: 'Arabic',
    releaseYear: 2024,
    releaseMonth: 5,
    rating: 8.6,
    status: 'Completed',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 80,
    trending: 78,
    episodeCount: 14,
    currentEpisode: 14
  },

  // ═══════════════════════════════════════════════════════════════
  // WEB SERIES
  // ═══════════════════════════════════════════════════════════════
  {
    title: 'Digital Detox',
    originalTitle: '',
    type: 'WEB_SERIES',
    description: 'Six strangers check into a remote digital detox retreat in the Swiss Alps, only to discover that the retreat is a social experiment with dark consequences.',
    genres: ['Thriller', 'Mystery', 'Drama'],
    tags: ['web-series', 'social-experiment', 'thriller', 'switzerland'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 3,
    rating: 8.1,
    status: 'Completed',
    platforms: ['Amazon Prime', 'Sony LIV'],
    popularity: 77,
    trending: 74,
    episodeCount: 8,
    currentEpisode: 8
  },
  {
    title: 'Startup Stories',
    originalTitle: '',
    type: 'WEB_SERIES',
    description: 'A comedic look at the chaotic world of tech startups in Bangalore, where a group of young entrepreneurs navigate funding failures, crazy co-founders, and the elusive unicorn dream.',
    genres: ['Comedy', 'Drama'],
    tags: ['web-series', 'startup', 'bangalore', 'comedy'],
    spokenLanguage: 'Hindi',
    releaseYear: 2024,
    releaseMonth: 6,
    rating: 8.3,
    status: 'Ongoing',
    platforms: ['Amazon Prime', 'Netflix'],
    popularity: 78,
    trending: 80,
    episodeCount: 12,
    currentEpisode: 12
  },
  {
    title: 'Coastal Crimes',
    originalTitle: '',
    type: 'WEB_SERIES',
    description: 'A detective in Goa investigates a string of mysterious deaths in the beach party scene, uncovering a drug trafficking network that reaches the highest levels of power.',
    genres: ['Crime', 'Thriller', 'Mystery'],
    tags: ['web-series', 'goa', 'crime', 'detective'],
    spokenLanguage: 'Hindi',
    releaseYear: 2024,
    releaseMonth: 1,
    rating: 7.9,
    status: 'Completed',
    platforms: ['Sony LIV', 'Netflix'],
    popularity: 73,
    trending: 69,
    episodeCount: 10,
    currentEpisode: 10
  },
  {
    title: 'Foodie Fight',
    originalTitle: '',
    type: 'WEB_SERIES',
    description: 'A competitive cooking web series where street food vendors from across India battle it out to create the ultimate dish, with each episode set in a different city.',
    genres: ['Reality', 'Food', 'Competition'],
    tags: ['web-series', 'cooking', 'street-food', 'india'],
    spokenLanguage: 'Hindi',
    releaseYear: 2024,
    releaseMonth: 9,
    rating: 7.5,
    status: 'Ongoing',
    platforms: ['Amazon Prime', 'Zee5'],
    popularity: 68,
    trending: 65,
    episodeCount: 16,
    currentEpisode: 16
  },
  {
    title: 'The Audition Room',
    originalTitle: '',
    type: 'WEB_SERIES',
    description: 'Set entirely in one audition room, each episode follows a different actor\'s high-stakes audition for a mysterious film, revealing their deepest insecurities and darkest secrets.',
    genres: ['Drama', 'Psychological', 'Anthology'],
    tags: ['web-series', 'audition', 'psychological', 'anthology'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 2,
    rating: 8.4,
    status: 'Ongoing',
    platforms: ['Amazon Prime', 'Netflix'],
    popularity: 71,
    trending: 68,
    episodeCount: 6,
    currentEpisode: 6
  },
  {
    title: 'Code of Silence',
    originalTitle: '',
    type: 'WEB_SERIES',
    description: 'A whistleblower at a top cybersecurity firm uncovers a global surveillance network. She must navigate a web of lies while protecting her family from those who will stop at nothing to silence her.',
    genres: ['Thriller', 'Drama', 'Tech'],
    tags: ['web-series', 'cybersecurity', 'whistleblower', 'surveillance'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 11,
    rating: 8.0,
    status: 'Completed',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 76,
    trending: 72,
    episodeCount: 8,
    currentEpisode: 8
  },
  {
    title: 'Monsoon Diaries',
    originalTitle: 'മൺസൂൺ ഡയറീസ്',
    type: 'WEB_SERIES',
    description: 'A heartwarming anthology series set in Kerala during monsoon season, where each episode tells a different love story connected by the rain.',
    genres: ['Romance', 'Drama', 'Anthology'],
    tags: ['web-series', 'kerala', 'romance', 'anthology'],
    spokenLanguage: 'Malayalam',
    releaseYear: 2024,
    releaseMonth: 7,
    rating: 8.2,
    status: 'Ongoing',
    platforms: ['Amazon Prime', 'Netflix'],
    popularity: 70,
    trending: 67,
    episodeCount: 10,
    currentEpisode: 10
  },

  // ═══════════════════════════════════════════════════════════════
  // ANIME
  // ═══════════════════════════════════════════════════════════════
  {
    title: 'Celestial Forge',
    originalTitle: '天の鍛冶場',
    type: 'ANIME',
    description: 'In a world where weapons are forged from starlight, a young blacksmith\'s apprentice discovers she can create weapons that rival the gods, drawing the attention of celestial beings.',
    genres: ['Animation', 'Fantasy', 'Action'],
    tags: ['anime', 'fantasy', 'blacksmith', 'gods'],
    spokenLanguage: 'Japanese',
    releaseYear: 2024,
    releaseMonth: 4,
    rating: 8.6,
    status: 'Ongoing',
    platforms: ['Crunchyroll', 'Netflix'],
    popularity: 89,
    trending: 87,
    episodeCount: 22,
    currentEpisode: 22
  },
  {
    title: 'Ghost Signal',
    originalTitle: 'ゴーストシグナル',
    type: 'ANIME',
    description: 'A group of high school students discovers they can communicate with the dead through a mysterious radio frequency. But each message comes with a price.',
    genres: ['Animation', 'Horror', 'Mystery'],
    tags: ['anime', 'supernatural', 'ghosts', 'school'],
    spokenLanguage: 'Japanese',
    releaseYear: 2024,
    releaseMonth: 7,
    rating: 7.8,
    status: 'Completed',
    platforms: ['Crunchyroll'],
    popularity: 80,
    trending: 76,
    episodeCount: 12,
    currentEpisode: 12
  },
  {
    title: 'Eternal Garden',
    originalTitle: '永遠の庭',
    type: 'ANIME',
    description: 'A gentle slice-of-life anime about an elderly gardener who tends a magical garden that grows memories instead of flowers, helping lost souls find peace.',
    genres: ['Animation', 'Drama', 'Fantasy'],
    tags: ['anime', 'slice-of-life', 'fantasy', 'emotional'],
    spokenLanguage: 'Japanese',
    releaseYear: 2025,
    releaseMonth: 1,
    rating: 8.9,
    status: 'Ongoing',
    platforms: ['Crunchyroll', 'Netflix'],
    popularity: 85,
    trending: 83,
    episodeCount: 8,
    currentEpisode: 8
  },
  {
    title: 'Thunder Academy',
    originalTitle: '雷鳴学園',
    type: 'ANIME',
    description: 'At an academy for elemental warriors, a boy with no elemental powers discovers he can absorb and nullify others\' abilities, making him both the weakest and the most dangerous student.',
    genres: ['Animation', 'Action', 'Comedy'],
    tags: ['anime', 'school', 'elemental', 'underdog'],
    spokenLanguage: 'Japanese',
    releaseYear: 2024,
    releaseMonth: 10,
    rating: 8.0,
    status: 'Ongoing',
    platforms: ['Crunchyroll', 'Netflix'],
    popularity: 82,
    trending: 79,
    episodeCount: 16,
    currentEpisode: 16
  },
  {
    title: 'Ramen Road',
    originalTitle: 'ラーメン道',
    type: 'ANIME',
    description: 'A young chef travels across Japan in a food truck, perfecting the art of ramen while learning life lessons from the colorful characters she meets along the way.',
    genres: ['Animation', 'Comedy', 'Food'],
    tags: ['anime', 'food', 'travel', 'comedy'],
    spokenLanguage: 'Japanese',
    releaseYear: 2024,
    releaseMonth: 2,
    rating: 8.4,
    status: 'Completed',
    platforms: ['Crunchyroll'],
    popularity: 81,
    trending: 77,
    episodeCount: 24,
    currentEpisode: 24
  },
  {
    title: 'Dragonheart Saga',
    originalTitle: 'ドラゴンハートサーガ',
    type: 'ANIME',
    description: 'In a world where humans and dragons lived in harmony, a young rider must unite the scattered dragon clans to defeat an ancient evil that threatens to consume the world.',
    genres: ['Animation', 'Fantasy', 'Adventure'],
    tags: ['anime', 'dragons', 'fantasy', 'adventure'],
    spokenLanguage: 'Japanese',
    releaseYear: 2025,
    releaseMonth: 4,
    rating: 8.7,
    status: 'Ongoing',
    platforms: ['Crunchyroll', 'Netflix', 'Hulu'],
    popularity: 90,
    trending: 91,
    episodeCount: 6,
    currentEpisode: 6
  },
  {
    title: 'Neo Tokyo Blues',
    originalTitle: 'ネオ東京ブルース',
    type: 'ANIME',
    description: 'A jazz musician in futuristic Neo Tokyo navigates the underground music scene while investigating the mysterious disappearance of his mentor.',
    genres: ['Animation', 'Drama', 'Mystery'],
    tags: ['anime', 'music', 'neo-tokyo', 'mystery'],
    spokenLanguage: 'Japanese',
    releaseYear: 2024,
    releaseMonth: 5,
    rating: 8.3,
    status: 'Completed',
    platforms: ['Crunchyroll', 'Netflix'],
    popularity: 79,
    trending: 75,
    episodeCount: 12,
    currentEpisode: 12
  },
  {
    title: 'The Alchemist\'s Daughter',
    originalTitle: '錬金術師の娘',
    type: 'ANIME',
    description: 'A young alchemist in a steampunk Victorian world searches for the legendary Philosopher\'s Stone to save her dying mother, facing dangerous creatures and rival alchemists.',
    genres: ['Animation', 'Fantasy', 'Adventure'],
    tags: ['anime', 'alchemy', 'steampunk', 'adventure'],
    spokenLanguage: 'Japanese',
    releaseYear: 2025,
    releaseMonth: 7,
    rating: 8.5,
    status: 'Ongoing',
    platforms: ['Crunchyroll', 'Netflix'],
    popularity: 83,
    trending: 80,
    episodeCount: 4,
    currentEpisode: 4
  },

  // ═══════════════════════════════════════════════════════════════
  // DOCUMENTARIES
  // ═══════════════════════════════════════════════════════════════
  {
    title: 'Deep Blue Frontier',
    originalTitle: '',
    type: 'DOCUMENTARY',
    description: 'A breathtaking exploration of the deepest ocean trenches, revealing bizarre creatures and ecosystems that challenge our understanding of life on Earth.',
    genres: ['Documentary', 'Nature', 'Science'],
    tags: ['ocean', 'deep-sea', 'marine-biology', 'nature'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 4,
    rating: 9.1,
    status: 'Completed',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 82,
    trending: 78,
    episodeCount: 6,
    currentEpisode: 6
  },
  {
    title: 'Masters of Light',
    originalTitle: '',
    type: 'DOCUMENTARY',
    description: 'A stunning documentary following the world\'s most celebrated cinematographers as they reveal the art, science, and passion behind creating iconic film imagery.',
    genres: ['Documentary', 'Film', 'Art'],
    tags: ['cinematography', 'film', 'art', 'behind-the-scenes'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 8,
    rating: 8.7,
    status: 'Released',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 74,
    trending: 70,
    episodeCount: 4,
    currentEpisode: 4
  },
  {
    title: 'Forgotten Kingdoms',
    originalTitle: '',
    type: 'DOCUMENTARY',
    description: 'An archaeological journey through lost civilizations across Africa, uncovering the sophisticated empires that history has overlooked.',
    genres: ['Documentary', 'Historical', 'Science'],
    tags: ['archaeology', 'africa', 'history', 'civilizations'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 1,
    rating: 8.9,
    status: 'Completed',
    platforms: ['BBC', 'Amazon Prime'],
    popularity: 78,
    trending: 74,
    episodeCount: 8,
    currentEpisode: 8
  },
  {
    title: 'Silicon Revolution',
    originalTitle: '',
    type: 'DOCUMENTARY',
    description: 'The untold story of the semiconductor revolution, from the invention of the transistor to the AI era, featuring interviews with the pioneers who shaped the digital world.',
    genres: ['Documentary', 'Technology', 'History'],
    tags: ['technology', 'silicon-valley', 'computing', 'innovation'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 2,
    rating: 8.5,
    status: 'Released',
    platforms: ['Apple TV+', 'Amazon Prime'],
    popularity: 71,
    trending: 67,
    episodeCount: 6,
    currentEpisode: 6
  },
  {
    title: 'Wanderlust: Asia',
    originalTitle: '',
    type: 'DOCUMENTARY',
    description: 'A visually stunning travel documentary series that traverses the hidden gems of Asia, from the steppes of Mongolia to the temples of Myanmar.',
    genres: ['Documentary', 'Travel', 'Culture'],
    tags: ['travel', 'asia', 'culture', 'adventure'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 6,
    rating: 8.3,
    status: 'Completed',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 76,
    trending: 72,
    episodeCount: 10,
    currentEpisode: 10
  },
  {
    title: 'The Quantum Leap',
    originalTitle: '',
    type: 'DOCUMENTARY',
    description: 'A mind-expanding documentary exploring the bizarre world of quantum physics, making complex science accessible through stunning visualizations and expert insights.',
    genres: ['Documentary', 'Science', 'Technology'],
    tags: ['quantum-physics', 'science', 'space', 'technology'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 5,
    rating: 8.8,
    status: 'Released',
    platforms: ['Netflix', 'Apple TV+'],
    popularity: 73,
    trending: 69,
    episodeCount: 4,
    currentEpisode: 4
  },
  {
    title: 'Culinary Crossroads',
    originalTitle: '',
    type: 'DOCUMENTARY',
    description: 'A mouth-watering journey through the spice routes of the world, exploring how trade winds shaped regional cuisines from Southeast Asia to the Mediterranean.',
    genres: ['Documentary', 'Food', 'Travel'],
    tags: ['food', 'spices', 'travel', 'culture'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 10,
    rating: 8.1,
    status: 'Completed',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 69,
    trending: 65,
    episodeCount: 8,
    currentEpisode: 8
  },
  {
    title: 'Arctic Melting Point',
    originalTitle: '',
    type: 'DOCUMENTARY',
    description: 'An urgent documentary following scientists on the front lines of climate change in the Arctic, documenting the rapid transformation of the polar ice caps.',
    genres: ['Documentary', 'Nature', 'Science'],
    tags: ['climate-change', 'arctic', 'environment', 'science'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 11,
    rating: 9.0,
    status: 'Released',
    platforms: ['Netflix', 'Disney+'],
    popularity: 77,
    trending: 73,
    episodeCount: 4,
    currentEpisode: 4
  },
  {
    title: 'Music of the Spheres',
    originalTitle: '',
    type: 'DOCUMENTARY',
    description: 'A mesmerizing exploration of the relationship between music and the cosmos, featuring musicians and astronomers who find harmony in the universe\'s patterns.',
    genres: ['Documentary', 'Music', 'Science'],
    tags: ['music', 'cosmos', 'science', 'art'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 8,
    rating: 8.6,
    status: 'Upcoming',
    platforms: ['Apple TV+', 'Amazon Prime'],
    popularity: 65,
    trending: 62,
    episodeCount: 4,
    currentEpisode: 0
  },
  {
    title: 'Urban Wild',
    originalTitle: '',
    type: 'DOCUMENTARY',
    description: 'Discover the surprising wildlife that thrives in the world\'s biggest cities, from leopards in Mumbai to falcons in New York and coyotes in Los Angeles.',
    genres: ['Documentary', 'Nature', 'Urban'],
    tags: ['wildlife', 'urban', 'nature', 'cities'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 3,
    rating: 8.4,
    status: 'Completed',
    platforms: ['Netflix', 'Amazon Prime'],
    popularity: 75,
    trending: 71,
    episodeCount: 6,
    currentEpisode: 6
  },
  {
    title: 'Codebreakers: The Next Generation',
    originalTitle: '',
    type: 'DOCUMENTARY',
    description: 'Follow the world\'s top cryptographers and ethical hackers as they race to develop quantum-proof encryption before our digital infrastructure becomes vulnerable.',
    genres: ['Documentary', 'Technology', 'Science'],
    tags: ['cybersecurity', 'encryption', 'quantum', 'hacking'],
    spokenLanguage: 'English',
    releaseYear: 2025,
    releaseMonth: 9,
    rating: 8.2,
    status: 'Upcoming',
    platforms: ['Netflix', 'Apple TV+'],
    popularity: 62,
    trending: 60,
    episodeCount: 4,
    currentEpisode: 0
  },
  {
    title: 'Rhythm of the Savannah',
    originalTitle: '',
    type: 'DOCUMENTARY',
    description: 'An intimate look at the wildlife of the African savannah filmed over two years, revealing never-before-captured behaviors of lions, elephants, and hyenas.',
    genres: ['Documentary', 'Nature', 'Wildlife'],
    tags: ['africa', 'wildlife', 'savannah', 'nature'],
    spokenLanguage: 'English',
    releaseYear: 2024,
    releaseMonth: 3,
    rating: 9.3,
    status: 'Completed',
    platforms: ['Disney+', 'Amazon Prime'],
    popularity: 84,
    trending: 80,
    episodeCount: 6,
    currentEpisode: 6
  }
];

// Attach a guaranteed, unique poster + backdrop image to every item.
const contentDataWithImages = contentData.map((item) => ({
  ...item,
  poster: posterFor(item.title),
  backdrop: backdropFor(item.title)
}));

async function seedContent() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log(`Connected to MongoDB: ${MONGO_URI}\n`);

    await Content.deleteMany({});
    console.log('✓ Cleared existing content\n');

    const inserted = await Content.insertMany(contentDataWithImages);
    console.log(`✓ Seeded ${inserted.length} content items\n`);

    // Sanity check: confirm every inserted doc has a poster and backdrop.
    const missingImages = await Content.countDocuments({
      $or: [
        { poster: { $in: [null, ''] } },
        { backdrop: { $in: [null, ''] } }
      ]
    });
    if (missingImages > 0) {
      console.warn(`⚠ Warning: ${missingImages} item(s) are missing an image!`);
    } else {
      console.log('✓ Verified: every item has a poster and backdrop image\n');
    }

    const movieCount = await Content.countDocuments({ type: 'MOVIE' });
    const tvCount = await Content.countDocuments({ type: 'TV_SERIES' });
    const webCount = await Content.countDocuments({ type: 'WEB_SERIES' });
    const animeCount = await Content.countDocuments({ type: 'ANIME' });
    const docCount = await Content.countDocuments({ type: 'DOCUMENTARY' });
    const upcomingCount = await Content.countDocuments({ status: 'Upcoming' });

    console.log('  Content Breakdown:');
    console.log(`  ${' '.repeat(25)}`);
    console.log(`  Movies:        ${movieCount}`);
    console.log(`  TV Series:     ${tvCount}`);
    console.log(`  Web Series:    ${webCount}`);
    console.log(`  Anime:         ${animeCount}`);
    console.log(`  Documentaries: ${docCount}`);
    console.log(`  ─────────────────────`);
    console.log(`  Total:         ${inserted.length}`);
    console.log(`  Upcoming:      ${upcomingCount}`);
    console.log('');
    console.log('✓ Seed complete!');

    process.exit(0);
  } catch (error) {
    console.error(`Seed failed: ${error.message}`);
    process.exit(1);
  }
}

seedContent();